# Generated by Django 3.1.2 on 2022-01-31 10:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20220131_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Romm',
            new_name='Room',
        ),
    ]
